### ISSUE TITLE
Incrementing values in ranges like Realtor.com app

### ISSUE THREAD

**Issue by Daemon-Devarshi** [muZZkat/NMRangeSlider#59]
I am trying to implement the functionality similar to Price slider in Realtor.com app. In that minPrice is 0 and max is 10,000,000. It increments values in below ranges:
1. 0 - 100,000 it increments by 10,000
2. 100,000 - 500,000 it increments by 25,000
3. 500,000 - 1,000,000 it increments by 50,000
4. 1,000,000 onwards it increments by 250,000

Please suggest how can I achieve desired behavior using NMRangeSlider.

**Comment by muZZkat** [comment]
Just use a standard range, eg 0-1 and set the step size to you your desired number of steps. You will then just need to calculate the $ value based on the normalized range. 

You don't actually want to change the slider step size
